$schema: https://json-schema.org/draft/2019-09/hyper-schema
title: Curious Crowd
description: Curious Crowd
x-codeGenie:
  region: us-west-2
  permissionModel: Global
  defaultAuthRoute: /expenses
  entities:
    - user
    # - post
    # - comment
    - expense
    - income
    # - category
    - note
    # - commentUpvote
    # - postUpvote
definitions:
  user:
    $ref: ./entities/user.yml
  # post:
  #   $ref: ./entities/post.yml
  # comment:
  #   $ref: ./entities/comment.yml
  expense:
    $ref: ./entities/expense.yml
  income:
    $ref: ./entities/income.yml
  note:
    $ref: ./entities/note.yml
  # category:
  #   $ref: ./entities/category.yml
  # postUpvote:
  #   $ref: ./entities/post-upvote.yml
  # commentUpvote:
  #   $ref: ./entities/comment-upvote.yml
